### ISSUE TITLE
apple maps annotation typings error

### ISSUE THREAD

**Issue by vikingschris** [ihor-zinchenko/ngx-apple-maps#12]
**Error**: node_modules/ngx-apple-maps/lib/components/apple-maps-annotation/apple-maps-annotation.component.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

**Angular:** 8.2.3
**npm:** 7.5.6
**node:** v12.13.0
**ngx-apple-maps:** ^0.1.19

I copied the cdn mapkitjs code into a local file and added to scripts in angular json file. I installed mapkit-typescript and added it to tsconfig.json typeRoots. I added mapkit to types in tsconfig.app.json.

Need help resolving this issue because the angular app is failing to compile.

**Comment by webtimo-de** [comment]
Hey, maybe you want to use a renewed version of it. I rebuilt the project on Angular 16 and Ivy. And I also revised the typings there. Maybe this will help you (:

```shell
npm install ngx-apple-mapkit
```

https://github.com/webtimo-de/ngx-apple-mapkit

**Comment by ihor-zinchenko** [comment]
Fixed in v1.0.0. Older versions are no longer supported. It will be released soon.
