### ISSUE TITLE
Example not rendering map

### ISSUE THREAD

**Issue by daniel-scheibe-hagebau** [ihor-zinchenko/ngx-apple-maps#5]
I cant get the example to render the Map.

I tried to update to ngx-apple-maps 0.9 because 0.8 cant be installed from npm, the map init was a success because I got the apple warnings about the token lifetime ...

```
[MapKit] Authorization token with expiration date greater than 1 year is not recommended in production environments.
n — mapkit.js:3:2858 ) 
```

I also tried to install the latest version from ngx-apple-maps but there was some error with the longitude and latitude getter, a adjust them to dont use the getter and setter. I changed the Options and Settings after it was renamed. But it is still not rendering.

I also bootstraped an actually angular version ( ~10.0.4 ) with the latest ngx-apple-maps but it also not rendering the map after the successful init.

where is the catch? it is my mistake or is this package broken?

**Comment by IhorVimmi** [comment]
@daniel-scheibe-hagebau hi, i i'll update package ASAP and check your issue
I recomend to use latest version ngx-apple-maps
Current version is 0.1.6

**Comment by daniel-scheibe-hagebau** [comment]
hey @ihor-zinchenko, I still cant get current version 0.1.12 running, what about the example project update?

**Comment by daniel-scheibe-hagebau** [comment]
Now it is working, the div for the map was broken... is up and running with the 0.1.12.

**Comment by ihor-zinchenko** [comment]
@daniel-scheibe-hagebau im on it

**Comment by ihor-zinchenko** [comment]
@daniel-scheibe-hagebau now example works correctly
