### ISSUE TITLE
Dynamically Set Map Center

### ISSUE THREAD

**Issue by Charliebegood** [ihor-zinchenko/ngx-apple-maps#6]
Hi,

I can't figure out a way to set the map's center after it has loaded. I have a constantly changing list of locations and when a one is added or removed I need the reset the map's center.

Thanks!

**Comment by Charliebegood** [comment]
Sorry, I only read the README.md on the GitHub repository which isn't up to date. I found the answer on the npm page.

**Comment by ihor-zinchenko** [comment]
@Charliebegood thank you for your question, i already update readme.md
